### ISSUE TITLE
selenuim test error

### ISSUE THREAD

**Issue by wisebearlu** [DedInc/selenium_dolphin#10]
driver = dolphin.get_driver(options=options, port=port)
driver.get('https://google.com/')
print(driver.title)
driver.quit()

TypeError: __init__() got an unexpected keyword argument 'service'
driver = webdriver.Chrome(service=Service(driver_path), options=options)

**Comment by DedInc** [comment]
Works!

![image](https://github.com/DedInc/selenium_dolphin/assets/41906303/6cd35fb6-1330-46ea-b5ad-b6659ede1e58)

Just use Selenium 4.x version!
