### ISSUE TITLE
Selenium driver gets stuck

### ISSUE THREAD

**Issue by Manikseam** [DedInc/selenium_dolphin#12]
When running the code about selenium provided in the quickstart section, it feels that the driver gets stuck after the first navigation to a webpage. It doesn't show any error message in the console. It just doesn't execute any driver related functions.

Also I cannot execute commands like `driver.quit()`, `driver.title` or `driver.save_screenshot("test.png")`.

Chromedriver version: 122

When closing the window, i get the following error:
<img width="1121" alt="Bildschirmfoto 2024-03-06 um 17 05 39" src="https://github.com/DedInc/selenium_dolphin/assets/126292904/92207f28-c0e9-42a6-aed0-42bf34e11797">

**Comment by DedInc** [comment]
you are right, selenium something began to hang and page loading for some reason is not detected, you can use this trick: disable load strategy, setting it to none and detect the loading of any elements through WebWait, it is generally good practice in web automation.

```python
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

options = Options()
options.page_load_strategy = 'none'

driver = dolphin.get_driver(options=options, port=port)
driver.get('https://google.com/')
wait = WebDriverWait(driver, 10)
wait.until(EC.visibility_of_element_located((By.CSS_SELECTOR, 'img[alt="Google"]')))

print(driver.title)
driver.save_screenshot('test.png')
driver.quit()
```
