### ISSUE TITLE
DebuggerAdress port

### ISSUE THREAD

**Issue by lorant124** [DedInc/selenium_dolphin#15]
Hi, thanks for the library.

I would like to use it in headless mode and inspect pages with Chrome. Is it possible to change the debug address port? When I start the run profile, the port is generated randomly, and every time I restart or start the script, I must configure Chrome's target discovery settings to new ports from:
`port = response['automation']['port']`

I would like to set up fixed ports and specify them. In a normal ChromeDriver, it works like this: 
`options.add_argument(f'--remote-debugging-port={debug_port}')`

I tried in Dolphin to change it, for example, with: 
`dolphin.get_driver(options=options, port=9992) `
and got an error:
_Message: unknown error: cannot connect to Chrome at 127.0.0.1:9992
from Chrome not reachable._

with generated ports :
`port = response['automation']['port']
dolphin.get_driver(options=options, port=port)
`
it works well. 
Thank you

**Comment by DedInc** [comment]
Unfortunately, Dolphin's documentation doesn't have custom ports setup for debugging, we'll have to look for another solution
