### ISSUE TITLE
set a download folder

### ISSUE THREAD

**Issue by luizlgj** [DedInc/selenium_dolphin#16]
How do I define a default folder for downloads made through this profile, using the API.

In Selenium, I do it like this.

```
DOWNLOAD_FOLDER = "downloads"
options = Options()
prefs = {"download.default_directory": os.path.join(os.getcwd(), DOWNLOAD_FOLDER)}
options.add_experimental_option("prefs", prefs)
```

But how can we define it using the selenium_dolphin API

I tried the code above, and it didn't work for selenium_dolphin api

**Comment by DedInc** [comment]
It is unlikely that this can be done, I have not found it anywhere, however, you can try to write a function to find this folder and transfer files if required
