### ISSUE TITLE
while adding fingerprint, Dolphin Anty software shows different options.

### ISSUE THREAD

**Issue by akshmalhotra844** [DedInc/selenium_dolphin#2]
Canvas: Noise
WebGL: Noise
Client Rects: Noise
Mac Address: Manually
Device Name: Manually
Screen: Manual
Media devices: Manual

can't see these options in the Python SDK provided, but in the Software options are available.
![image](https://github.com/DedInc/selenium_dolphin/assets/91355723/22aa3db2-fe09-49fa-ac9b-9cb5f8c4eafd)

	def fingerprint_to_profile(self, name, tags=[], fingerprint={}):
	  data = dict()
	  data['name'] = name
	  data['tags'] = tags
	  
	  data['platform'] = fingerprint['os']['name'].lower()
	  data['browserType'] = 'anty'
	  data['mainWebsite'] = 'none'

	  data['useragent'] = {
	    'mode': 'manual',
	    'value': fingerprint['userAgent']
	  }

	  data['deviceName'] = {
	    'mode': 'off',
	    'value': None
	  }

	  data['macAddress'] = {
	    'mode': 'off', 
	    'value': None
	  }

	  data['webrtc'] = {
	    'mode': 'altered',
	    'ipAddress': None
	  }

	  data['canvas'] = {
	    'mode': 'real'
	  }

	  data['webgl'] = {
	    'mode': 'real'
	  }

	  data['webglInfo'] = {
	    'mode': 'manual',
	    'vendor': fingerprint['webgl']['unmaskedVendor'],
	    'renderer': fingerprint['webgl']['unmaskedRenderer'],
	    'webgl2Maximum': fingerprint['webgl2Maximum']
	  }

	  data['webgpu'] = {
	    'mode': 'manual' 
	  }

	  data['clientRect'] = {
	    'mode': 'real'
	  }

	  data['timezone'] = {
	    'mode': 'auto',
	    'value': None
	  }

	  data['locale'] = {
	    'mode': 'auto',
	    'value': None
	  }

	  data['proxy'] = {}

	  data['geolocation'] = {
	    'mode': 'auto',
	    'latitude': None,
	    'longitude': None,  
	    'accuracy': None
	  }

	  data['cpu'] = {
	    'mode': 'manual',
	    'value': fingerprint['hardwareConcurrency']
	  }

	  data['memory'] = {
	    'mode': 'manual',
	    'value': fingerprint['deviceMemory']
	  }

	  data['screen'] = {
	    'mode': 'real',
	    'resolution': None
	  }

	  data['audio'] = {
	    'mode': 'real'
	  }

	  data['mediaDevices'] = {
	    'mode': 'real',
	    'audioInputs': None,
	    'videoInputs': None,
	    'audioOutputs': None
	  }

	  data['ports'] = {
	    'mode': 'protect',
	    'blacklist': '3389,5900,5800,7070,6568,5938'
	  }

	  data['doNotTrack'] = False
	  data['args'] = []
	  data['platformVersion'] = fingerprint['platformVersion']
	  data['uaFullVersion'] = fingerprint['browser']['version']
	  data['login'] = ''
	  data['password'] = ''
	  data['appCodeName'] = 'Mozilla'
	  data['platformName'] = 'MacIntel'
	  data['connectionDownlink'] = fingerprint['connection']['downlink']
	  data['connectionEffectiveType'] = fingerprint['connection']['effectiveType']
	  data['connectionRtt'] = fingerprint['connection']['rtt']
	  data['connectionSaveData'] = fingerprint['connection']['saveData']
	  data['cpuArchitecture'] = fingerprint['cpu']['architecture']
	  data['osVersion'] = '10.15.7'
	  data['vendorSub'] = ''
	  data['productSub'] = fingerprint['productSub']
	  data['vendor'] = fingerprint['vendor']
	  data['product'] = fingerprint['product']

**Comment by DedInc** [comment]
![image](https://github.com/DedInc/selenium_dolphin/assets/41906303/0428edd5-93c9-4ad4-a2f2-b401d7fc61fe)
and what do you think this is?

**Comment by akshmalhotra844** [comment]
can you please provide a solution in Python on how I can set these values using Python script?


![image](https://github.com/DedInc/selenium_dolphin/assets/91355723/45effb32-5a8c-4012-b167-58174209c0ec)

because I am not able to solve it I have tried many ways but never worked.

![image](https://github.com/DedInc/selenium_dolphin/assets/91355723/78ad20bd-a41e-4591-93ab-a9292151ba39)
 
 Thanks in advance.
